[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 -m http.server ${PORT:-8000}"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "8000"
